import type { HeroDefinition, LevelDefinition } from './types';

export const HEROES: HeroDefinition[] = [
  { id:'bud', name:'Bud', title:'The Brawler', color:0xd47735, stats:{might:8,grit:8,agility:4,awareness:5,ingenuity:5,resolve:6}, skill:'Timberline Takedown', skillDescription:'A crushing charge that staggers bosses and scatters mobs.', voice:'Steady, dry, protective' },
  { id:'erin', name:'Erin', title:'The Trailblazer', color:0x4fa8a0, stats:{might:5,grit:6,agility:8,awareness:8,ingenuity:5,resolve:4}, skill:'Backtrail', skillDescription:'A rapid evasive dash that exposes traps and enemy weak points.', voice:'Decisive, observant, quietly funny' },
  { id:'gin', name:'Gin', title:'The Tactician', color:0xb585c6, stats:{might:5,grit:5,agility:5,awareness:6,ingenuity:8,resolve:7}, skill:'Field Expedient', skillDescription:'Drops a scrap charge that detonates after a short delay.', voice:'Precise, inventive, impossible to rattle' }
];

const raw: Array<[string,string,string,string,string,string,string[],number,number,number]> = [
 ['The Fallen Mill','Ruined sawmill','The mill is gone. The night sky is gone. Only Moxie, a splintered break room, and a cheerful mechanical voice remain.','Find Moxie and reach the freight lift.','Movement, melee, and companion basics','The Splinter Foreman',['Sawmites','Rafter Bats'],0x26312d,0x5d4936,0xd26935],
 ['Culvert Country','Flooded service tunnels','Boot prints vanish beneath black water. Somebody else survived—and something followed them downstream.','Restore three pumps and open the floodgate.','Ranged combat, water hazards, and scouting','Drainback',['Silt Skulkers','Pipe Eels'],0x17313a,0x38515a,0x4d9e91],
 ['The Safety Department','Weaponized training center','The Ledger schedules a mandatory orientation. Failure to comply is punishable by teeth.','Collect three safety seals and pass inspection.','Traps, achievements, rest rooms, and build choices','Inspector Nine',['Compliance Drones','Cone Mimics'],0x302e28,0x655f4b,0xe1aa45],
 ['Root Cellar Warrens','Fungal root maze','The roots remember the houses above, but they have confused kitchens with graves.','Burn the spore hearts.','Poison, crafting, and destructible roots','Mother Mulch',['Sporelings','Root Hounds'],0x243421,0x526246,0x7f934f],
 ['The Freight Maze','Impossible rail yard','Cargo cars carry bottled laughter, missing names, and one still-ringing telephone.','Route a memory car to the forbidden siding.','Switches, moving carts, and timing','The Yardmaster',['Rail Gnashers','Ticket Wraiths'],0x272d35,0x59616d,0xb55c43],
 ['Kennel Zero','Companion testing laboratory','The Underworks lists Moxie as inventory. Moxie has objections.','Free the classified companions.','Advanced companion commands','The Breeder',['Copy Dogs','Leash Drones'],0x29343a,0x61747a,0xc97287],
 ['Barracks of Echoes','Corrupted military archive','The halls replay orders no one gave and battles no one fought.','Silence the four echo transmitters.','Cover, alarms, and stealth','Captain Playback',['Echo Troopers','Medal Leeches'],0x28303b,0x556071,0x5c82a8],
 ['The Greenchain','Vertical lumberworks','A perfect copy of the mill runs forever, feeding logs into a door marked HUMAN RESOURCES.','Stop the chain without crushing trapped workers.','Conveyors, machinery, and log rolling','Widowmaker',['Chainlings','Bark Skins'],0x2e2922,0x594d3e,0xcf7e35],
 ['Rest Stop Eternal','Endless roadside oasis','The coffee is hot, the bathrooms are clean, and nobody has managed to leave since 1987.','Break the rest stop loop.','Investigation, disguises, and vending buffs','The Night Manager',['Mop Things','Repeat Customers'],0x28343b,0x6d6658,0xddc463],
 ['The Bone Orchard','Forest of stolen histories','Every tree whispers a life. Cutting a path means choosing which memories survive.','Recover the Split Pine memory core.','Branching routes and moral choices','The Genealogist',['Name Crows','Marrow Deer'],0x2b272d,0x574b59,0xc16b79],
 ['Boiler Borough','Industrial NPC settlement','Workers keep the heat flowing because the Ledger says the cold outside is worse.','Prevent a catastrophic pressure purge.','Factions, escorts, heat, and pressure','Union Breaker X',['Cinder Clerks','Valve Brutes'],0x34251e,0x6b4834,0xe36b32],
 ['The Flooded Archive','Submerged records vault','The last escape plan waits under rising water, redacted one survivor at a time.','Recover three plan fragments.','Oxygen, diving routes, and lore','The Redactor',['Inkfish','Drowned Indexers'],0x142a35,0x31566a,0x7455a3],
 ['The Menagerie Market','Creature bazaar','Everything is for sale, including directions, loyalties, and tomorrow’s boss.','Earn or steal a route token.','Trading, reputation, and arena challenges','Auctioneer Vell',['Gavel Imps','Cagebacks'],0x332a35,0x665472,0xd79a46],
 ['Faultline Chapel','Machine-worshipping settlement','The congregation calls captivity a blessing. Their prophet knows the machine is listening.','Expose or empower the false saint.','Illusions, alliances, and resolve','Saint Static',['Choir Sparks','Faith Eaters'],0x25263b,0x4d5274,0xd9d45e],
 ['The Long Dark Shift','Lightless maintenance sector','The Ledger turns off the lights to improve morale. Something applauds in the dark.','Relight six emergency beacons.','Sound cues, scarcity, and limited vision','The Lamplighter',['Hush Crawlers','Bulb Thieves'],0x11131a,0x35394c,0xf0b64c],
 ['War Room Below','Subterranean battlefield','Three factions want the control map. None of them agree on who counts as human.','Choose an ally and seize the command table.','Large battles and tactical objectives','General Ledger',['Map Knights','Orderlies'],0x292a31,0x515367,0xb84949],
 ['The Upside-Down Forest','Gravity-broken wilderness','Roots hang from the sky and rain falls in both directions. Moxie is delighted.','Stabilize the gravity anchors.','Gravity zones and aerial threats','Crownshatter Elk',['Cloud Wolves','Falling Owls'],0x1c3033,0x3e6766,0x65b7a6],
 ['The Memory Sawmill','Personal reconstruction','The machine offers a perfect past with one minor improvement: no freedom.','Reject the perfected memory.','Hero-specific trials','The Other Foreman',['Regret Shavings','Perfect Coworkers'],0x342a29,0x654f45,0xe18a4f],
 ['The Audit','Adaptive gauntlet','Every shortcut, mercy, failure, and absurd achievement receives a final score.','Survive the review.','Consequences and adaptive encounters','The Final Reviewer',['Audit Hounds','Red Pens'],0x2c252b,0x5e4554,0xd14b64],
 ['The Heart Ledger','Underworks core','The machine does not want to kill a foreman. It wants to hire one.','Choose the fate of the Underworks.','Multi-phase finale and ending choice','The Underworks Core',['Heart Gears','Memory Copies'],0x211f27,0x504758,0xf1d37a]
];
export const LEVELS: LevelDefinition[] = raw.map((v,i)=>({id:i+1,title:v[0],environment:v[1],story:v[2],objective:v[3],mechanic:v[4],boss:v[5],enemyNames:v[6],floorColor:v[7],wallColor:v[8],bossColor:v[9]}));
